### ISSUE TITLE
ValueError: Not find vision tower: ./model_zoo/LAVIS/eva_vit_g.pth

### ISSUE THREAD

**Issue by MasonLi** [dvlab-research/LLaMA-VID#11]
when i try to chat about a short video use the cli command. I encountered this problem. Here is the detailed log:
[INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/data/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/user_code/LLaMA-VID/llamavid/serve/cli.py", line 137, in <module>
    main(args)
  File "/workspace/user_code/LLaMA-VID/llamavid/serve/cli.py", line 39, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit)
  File "/workspace/user_code/LLaMA-VID/llamavid/model/builder.py", line 56, in load_pretrained_model
    model = LlavaLlamaAttForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/data/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/workspace/user_code/LLaMA-VID/llamavid/model/language_model/llava_llama_vid.py", line 44, in __init__
    self.model = LlavaAttLlamaModel(config)
  File "/workspace/user_code/LLaMA-VID/llamavid/model/language_model/llava_llama_vid.py", line 37, in __init__
    super(LlavaAttLlamaModel, self).__init__(config)
  File "/workspace/user_code/LLaMA-VID/llamavid/model/llamavid_arch.py", line 46, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=True)
  File "/workspace/user_code/LLaMA-VID/llamavid/model/multimodal_encoder/builder.py", line 11, in build_vision_tower
    raise ValueError(f'Not find vision tower: {vision_tower}')
ValueError: Not find vision tower: ./model_zoo/LAVIS/eva_vit_g.pth
 can you help me with this error?

**Comment by wcy1122** [comment]
Hello. You can download EVA-ViT-G backbone from [here](https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth) and put it to `./model_zoo/LAVIS/eva_vit_g.pth`

**Comment by sykuann** [comment]
the model is downloaded and in the path but the error persist. Do i need to change the file path config?
