### ISSUE TITLE
AttributeError: 'Conversation' object has no attribute 'get_videos'

### ISSUE THREAD

**Issue by zhangningboo** [dvlab-research/LLaMA-VID#28]
2023-12-25 08:27:40 | INFO | gradio_web_server | http_bot. ip: 127.0.0.1
2023-12-25 08:27:40 | INFO | gradio_web_server | model_name: llama-vid-13b-full-224-video-fps-1, worker_addr: http://localhost:7373
2023-12-25 08:27:40 | ERROR | stderr | Traceback (most recent call last):
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/routes.py", line 437, in run_predict
2023-12-25 08:27:40 | ERROR | stderr |     output = await app.get_blocks().process_api(
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/blocks.py", line 1352, in process_api
2023-12-25 08:27:40 | ERROR | stderr |     result = await self.call_function(
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/blocks.py", line 1093, in call_function
2023-12-25 08:27:40 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/utils.py", line 341, in async_iteration
2023-12-25 08:27:40 | ERROR | stderr |     return await iterator.__anext__()
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/utils.py", line 334, in __anext__
2023-12-25 08:27:40 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-12-25 08:27:40 | ERROR | stderr |     return await get_asynclib().run_sync_in_worker_thread(
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-12-25 08:27:40 | ERROR | stderr |     return await future
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-12-25 08:27:40 | ERROR | stderr |     result = context.run(func, *args)
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/conda/envs/llamavid/lib/python3.10/site-packages/gradio/utils.py", line 317, in run_sync_iterator_async
2023-12-25 08:27:40 | ERROR | stderr |     return next(iterator)
2023-12-25 08:27:40 | ERROR | stderr |   File "/opt/workspace/LLaMA-VID/llamavid/serve/gradio_web_server.py", line 200, in http_bot
2023-12-25 08:27:40 | ERROR | stderr |     all_videos = state.get_videos()
2023-12-25 08:27:40 | ERROR | stderr | AttributeError: 'Conversation' object has no attribute 'get_videos'

**Comment by zhangningboo** [comment]
start controller:
```shell
$ python -m llamavid.serve.controller --host 0.0.0.0 --port 7272
```
start worker:
```shell
$ python -m llamavid.serve.model_worker --host 0.0.0.0 --controller http://localhost:7272 --port 7373 --worker http://localhost:7373 --model-path /opt/hf_model/model/YanweiLi/llama-vid-13b-full-224-video-fps-1
```
start server:
```shell
$ python -m llamavid.serve.gradio_web_server --controller http://localhost:7272 --model-list-mode reload --port 7171
```
Model: [YanweiLi/llama-vid-13b-full-224-video-fps-1](https://huggingface.co/YanweiLi/llama-vid-13b-full-224-video-fps-1)

**Comment by zhangningboo** [comment]
[eva_vit_g](https://storage.googleapis.com/sfr-vision-language-research/LAVIS/models/BLIP2/eva_vit_g.pth)
[bert-base-uncased](https://huggingface.co/bert-base-uncased/tree/main)

**Comment by wcy1122** [comment]
Hi. The `get_video` function is written [here](https://github.com/dvlab-research/LLaMA-VID/blob/main/llamavid/conversation.py#L109). Maybe you can check the corresponding file and see if you have pulled the latest code.
