### ISSUE TITLE
OSError: It looks like the config file at './model_zoo/LAVIS/eva_vit_g.pth' is not a valid JSON file

### ISSUE THREAD

**Issue by dragen1860** [dvlab-research/LLaMA-VID#29]
Dear all:
  thanks for sharing this great work. 
  when i try to run your demo code on video, an error occures:
```
Traceback (most recent call last):
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/sdb/long/lmm/LLaMA-VID/llamavid/serve/cli.py", line 137, in <module>
    main(args)
  File "/media/sdb/long/lmm/LLaMA-VID/llamavid/serve/cli.py", line 39, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit)
  File "/media/sdb/long/lmm/LLaMA-VID/llamavid/model/builder.py", line 79, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/llava/model/language_model/llava_llama.py", line 46, in __init__
    self.model = LlavaLlamaModel(config)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/llava/model/language_model/llava_llama.py", line 38, in __init__
    super(LlavaLlamaModel, self).__init__(config)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/llava/model/llava_arch.py", line 33, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=True)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/llava/model/multimodal_encoder/builder.py", line 9, in build_vision_tower
    return CLIPVisionTower(vision_tower, args=vision_tower_cfg, **kwargs)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/llava/model/multimodal_encoder/clip_encoder.py", line 20, in __init__
    self.cfg_only = CLIPVisionConfig.from_pretrained(self.vision_tower_name)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/transformers/models/clip/configuration_clip.py", line 239, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/transformers/configuration_utils.py", line 617, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/media/sdb/long/conda/envs/llamavid/lib/python3.10/site-packages/transformers/configuration_utils.py", line 705, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at './model_zoo/LAVIS/eva_vit_g.pth' is not a valid JSON file.
```

However, i am sure that the files './model_zoo/LAVIS/eva_vit_g.pth'  existed! 
anyone help me? thank you.

**Comment by wcy1122** [comment]
>   File "/media/sdb/long/lmm/LLaMA-VID/llamavid/model/builder.py", line 79, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)

Hello. based on the error above, it looks like your code run through [this branch](https://github.com/dvlab-research/LLaMA-VID/blob/main/llamavid/model/builder.py#L58) rather than [this branch](https://github.com/dvlab-research/LLaMA-VID/blob/main/llamavid/model/builder.py#L42). Make sure that the folder name of your model contains 'vid'.

**Comment by dragen1860** [comment]
> > File "/media/sdb/long/lmm/LLaMA-VID/llamavid/model/builder.py", line 79, in load_pretrained_model
> > model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
> 
> Hello. based on the error above, it looks like your code run through [this branch](https://github.com/dvlab-research/LLaMA-VID/blob/main/llamavid/model/builder.py#L58) rather than [this branch](https://github.com/dvlab-research/LLaMA-VID/blob/main/llamavid/model/builder.py#L42). Make sure that the folder name of your model contains 'vid'.

hI,thanks for your tips. I change the model path to contains `vid` : `pretrained/llama-vid-7b-full-224-video-fps-1/` and it finally works. That's the `   if 'vid' in model_name.lower():` logic  did not match problem. 
thank you very much.
