### ISSUE TITLE
Finetune Dataset like COCO, GQA, etc.

### ISSUE THREAD

**Issue by Hambaobao** [dvlab-research/LLaMA-VID#30]
Hello, thanks for your great work. I would like to inquire about the datasets used during the finetuning phase of your model. Specifically, I'm interested in knowing if datasets like `COCO`, `GQA`, `OCR_VQA`, `TextVQA`, and `VG` were utilized. My confusion arises from the fact that these datasets are not mentioned in the **Preparation Dataset** section, yet they appear in the `data/LLaMA-VID-Finetune/` directory. Could you please provide some clarification on this?

Additionally, if these datasets were indeed used for finetuning, could you offer some guidance on how to download and format them? 🥹

**Comment by yanwei-li** [comment]
Hi, thanks for your interest in our work. For the instruction fine-tuning, we adopt the image-based dataset in LLaVA, you can download and organize them according to the `Visual Instruction Tuning` section in [README](https://github.com/haotian-liu/LLaVA/blob/main/README.md).

**Comment by Hambaobao** [comment]
Thank you for your response. 👍
I have another question and would appreciate your further explanation. Could you please clarify the structure of the `data/LLaMA-VID-Pretrain/images` and `data/LLaMA-VID-Pretrain/videos` directories? The **Preparation** section seems to lack this information, and specifically, I have 2 points of confusion:
1. Regarding the `data/LLaMA-VID-Pretrain/images` directory, I downloaded images from [LLaVA-pretrain-images.zip](https://huggingface.co/datasets/liuhaotian/LLaVA-CC3M-Pretrain-595K/blob/main/images.zip), but I noticed that in `llava_558k_with_webvid.json`, one of the data entries lists the image path as `00037/000378145.jpg`. How is this path structured?
2. Regarding the `data/LLaMA-VID-Pretrain/videos` directory, I used the script from [webvid_download_script](https://github.com/m-bain/webvid/issues/4) to download the 2.5M subset of videos from [webvid](https://maxbain.com/webvid-dataset/). However, I noticed that in `llava_558k_with_webvid.json`, one of the data entries lists the video path as `000351_000400/3827210.mp4`. How is this path determined?

**Comment by Hambaobao** [comment]
> Thank you for your response. 👍 I have another question and would appreciate your further explanation. Could you please clarify the structure of the `data/LLaMA-VID-Pretrain/images` and `data/LLaMA-VID-Pretrain/videos` directories? The **Preparation** section seems to lack this information, and specifically, I have 2 points of confusion:
> 
> 1. Regarding the `data/LLaMA-VID-Pretrain/images` directory, I downloaded images from [LLaVA-CC3M-Pretrain-images.zip](https://huggingface.co/datasets/liuhaotian/LLaVA-CC3M-Pretrain-595K/blob/main/images.zip), but I noticed that in `llava_558k_with_webvid.json`, one of the data entries lists the image path as `00037/000378145.jpg`. How is this path structured?
> 2. Regarding the `data/LLaMA-VID-Pretrain/videos` directory, I used the script from [webvid_download_script](https://github.com/m-bain/webvid/issues/4) to download the 2.5M subset of videos from [webvid](https://maxbain.com/webvid-dataset/). However, I noticed that in `llava_558k_with_webvid.json`, one of the data entries lists the video path as `000351_000400/3827210.mp4`. How is this path determined?

I guess the images under `data/LLaMA-VID-Pretrain/images` should be downloaded from [LLaVA-Pretrain](https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain/blob/main/images.zip) instead of [LLaVA-CC3M-Pretrian](https://huggingface.co/datasets/liuhaotian/LLaVA-CC3M-Pretrain-595K/blob/main/images.zip)? 🤥

**Comment by yanwei-li** [comment]
Yes, for images used in LLaMA-VID pretrain, you need to download images from [LLaVA-Pretrain](https://huggingface.co/datasets/liuhaotian/LLaVA-Pretrain/blob/main/images.zip) and put all the images under `LLaMA-VID-Pretrain/images`. For the video, download the webvid and put all the subsets in downloaded `WebVid/data_2m/videos` to `LLaMA-VID-Pretrain/videos`. The path in the json like `000351_000400/3827210.mp4` denotes the relative path to `data/LLaMA-VID-Pretrain/videos`.

**Comment by Hambaobao** [comment]
Thank you for your response.
I used this [script](https://github.com/m-bain/webvid/issues/4) to download videos from [webvid](https://github.com/m-bain/webvid), and all the videos were directly placed in the 'LLaMA-VID-Pretrain/videos' directory without parent directories like `000351_000400/`, so I modified the script a bit:

```shell
csvcut -c videoid,contentUrl data/pretrain/LLaMA-VID/results_2M_train.csv \
  | sed 1d \
  | parallel --resume -v --joblog val.log --bar -j 126 'video_id=$(echo {} | cut -d , -f 1) && url=$(echo {} | cut -d , -f 2) && extension=${url##*.} && folder=$((video_id / 10000 / 50)) && start=$((folder * 50 + 1)) && end=$(( (folder + 1) * 50 )) && folder_name=$(printf "%06d_%06d" $start $end) && mkdir -p "data/pretrain/LLaMA-VID/videos/$folder_name" && wget --no-clobber -qO "data/pretrain/LLaMA-VID/videos/$folder_name/$video_id.$extension" $url'
```
I'm sharing the modified script here, so if anyone needs it, they can use it directly to download video from [webvid](https://github.com/m-bain/webvid).

**Comment by minuenergy** [comment]
is there any way to finetune only activityNet(video)?  
I want to jump to 2stage and FineTune on activitiyNet. 

bash scripts/video/train/stage_2_full_v7b_224_fps_1.sh 


I followed the scripts but I got this messages

Error in loading 12359, retrying...
Error in loading 30526, retrying...
Error in loading 86049, retrying...
Error in loading 38349, retrying...
Error in loading 47934, retrying...
Error in loading 14090, retrying...

and also confused about this preprocess function
preprocess_imgsp_v1 . 
what should i change to finetune on activitiynet?

**Comment by yanwei-li** [comment]
Hi, if you want to finetune the video only, you can directly delete other data that not contain the key `video` list in [this file](https://huggingface.co/datasets/YanweiLi/LLaMA-VID-Data/blob/main/llava_v1_5_mix665k_with_video_chatgpt.json) and only keep the video QA (actually in `loaded_json[-98138:]`). 
But it should be noted that only fine-tune video will cause performance in image and multi-turn conversation. 
And the `preprocess_imgsp_v1 ` aims to pad image token `<image>` to each question in multi-turn conversation. Because we generate different context tokens for each question, it is essential to append different visual tokens before answering questions.

**Comment by dragen1860** [comment]
> Hi, if you want to finetune the video only, you can directly delete other data that not contain the key `video` list in [this file](https://huggingface.co/datasets/YanweiLi/LLaMA-VID-Data/blob/main/llava_v1_5_mix665k_with_video_chatgpt.json) and only keep the video QA (actually in `loaded_json[-98138:]`). But it should be noted that only fine-tune video will cause performance in image and multi-turn conversation. And the `preprocess_imgsp_v1 ` aims to pad image token `<image>` to each question in multi-turn conversation. Because we generate different context tokens for each question, it is essential to append different visual tokens before answering questions.

hi, @yanwei-li , thanks. I also only want to finetunning on subset of webvid. I sampled a small subset of almost 423 videos from webvid dataset and only sample the 423 videos QA annotation from `llava_558k_with_webvid.json` into a new `toydb_from_webvid.json`.

but when i try to finnetunning on the toydb.json as 
```
#!/bin/bash
# CUDA_VISIBLE_DEVICES="4,5"

# at stage2, all models except the visual encoder will be finetunned.
deepspeed  --include localhost:4,5 llamavid/train/train_mem.py \
    --deepspeed ./scripts/zero2_offload.json \
    --version imgsp_v1 \
    --data_path ./data/LLaMA-VID-Finetune/toydb_from_webvid.json \
    --output_dir ./work_dirs/llama-vid-7b-full-224-video-fps-1  \
    --video_folder ./data/LLaMA-VID-Finetune/toydb_from_webvid \
    --vision_tower ./model_zoo/LAVIS/eva_vit_g.pth \
    --image_processor ./llamavid/processor/clip-patch14-224 \
    --model_name_or_path /media/sdb/long/lmm/CogVLM/vicuna-7b-v1.5/ \
    --pretrain_mm_mlp_adapter ./pretrained/llama-vid-7b-pretrain-224-video-fps-1/mm_projector.bin \
    --mm_projector_type mlp2x_gelu \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --image_aspect_ratio pad \
    --group_by_modality_length True \
    --video_fps 1 \
    --bert_type "qformer_pretrain" \
    --num_query 32 \
    --compress_type "mean" \
    --bf16 True \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 16 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to tensorboard

```

i get the following error:
```
  File "/media/sdb/long/lmm/LLaMA-VID/llamavid/train/llava_trainer.py", line 149, in __iter__
    indices = get_modality_length_grouped_indices(self.lengths, self.batch_size, self.world_size, generator=self.generator)
  File "/media/sdb/long/lmm/LLaMA-VID/llamavid/train/llava_trainer.py", line 80, in get_modality_length_grouped_indices
    lang_indices, lang_lengths = zip(*[(i, -l) for i, l in enumerate(lengths) if l < 0])
ValueError: not enough values to unpack (expected 2, got 0)
```

it seems because the code here all >0.

![image](https://github.com/dvlab-research/LLaMA-VID/assets/4252555/66ab979b-467c-4360-9e96-819213c8dc98)

So my question is, how to finetunning on videos only dataset? is anything goes wrong? thank you.

**Comment by yanwei-li** [comment]
Hi, it seems the error is caused from the format of your produced data. Please make sure the format of video data aligns with that in `llava_558k_with_webvid.json`.

**Comment by ShuoZhang2003** [comment]
> is there any way to finetune only activityNet(video)? I want to jump to 2stage and FineTune on activitiyNet.
> 
> bash scripts/video/train/stage_2_full_v7b_224_fps_1.sh
> 
> I followed the scripts but I got this messages
> 
> Error in loading 14090, retrying... Error in loading 31069, retrying...train() Error in loading 76494, retrying... Error in loading 30647, retrying...
> 
> File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 1204, in train trainer.train() File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train return inner_training_loop( File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1787, in _inner_training_loop for step, inputs in enumerate(epoch_iterator): File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 384, in **iter** current_batch = next(dataloader_iter) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in **next** data = self._next_data() File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data return self._process_data(data) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data data.reraise() File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 933, in **getitem** data_dict = preprocess( File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 772, in preprocess return preprocess_imgsp_v1(sources, tokenizer, has_image=has_image, refine_prompt=refine_prompt) File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 542, in preprocess_imgsp_v1 if roles[source[0]["from"]] != conv.roles[0]: KeyError: 0
> 
> and also confused about this preprocess function preprocess_imgsp_v1 . what should i change to finetune on activitiynet?

Hello, have you solved this problem?
I also encountered this error when trying to fine-tune on video and image data：

Original Traceback (most recent call last):
File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
data = fetcher.fetch(index)
File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 925, in __getitem__
data_dict = preprocess(
File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 774, in preprocess
return preprocess_imgsp_v1(sources, tokenizer, has_image=has_image, refine_prompt=refine_prompt)
File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 544, in preprocess_imgsp_v1
if roles[source[0]["from"]] != conv.roles[0]:
KeyError: 0

**Comment by carolchenyx** [comment]
> > is there any way to finetune only activityNet(video)? I want to jump to 2stage and FineTune on activitiyNet.
> > bash scripts/video/train/stage_2_full_v7b_224_fps_1.sh
> > I followed the scripts but I got this messages
> > Error in loading 14090, retrying... Error in loading 31069, retrying...train() Error in loading 76494, retrying... Error in loading 30647, retrying...
> > File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 1204, in train trainer.train() File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train return inner_training_loop( File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1787, in _inner_training_loop for step, inputs in enumerate(epoch_iterator): File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 384, in **iter** current_batch = next(dataloader_iter) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in **next** data = self._next_data() File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data return self._process_data(data) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data data.reraise() File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise raise exception KeyError: Caught KeyError in DataLoader worker process 0. Original Traceback (most recent call last): File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/opt/conda/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 933, in **getitem** data_dict = preprocess( File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 772, in preprocess return preprocess_imgsp_v1(sources, tokenizer, has_image=has_image, refine_prompt=refine_prompt) File "/workspace/mount/SSD_11T/minwoo/projects/LLM/LLaMA-VID/llamavid/train/train.py", line 542, in preprocess_imgsp_v1 if roles[source[0]["from"]] != conv.roles[0]: KeyError: 0
> > and also confused about this preprocess function preprocess_imgsp_v1 . what should i change to finetune on activitiynet?
> 
> Hello, have you solved this problem? I also encountered this error when trying to fine-tune on video and image data：
> 
> Original Traceback (most recent call last): File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/kas/.conda/envs/llamavid/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 925, in **getitem** data_dict = preprocess( File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 774, in preprocess return preprocess_imgsp_v1(sources, tokenizer, has_image=has_image, refine_prompt=refine_prompt) File "/home/kas/kas_workspace/shuozhang/LLaMA-VID/llamavid/train/train.py", line 544, in preprocess_imgsp_v1 if roles[source[0]["from"]] != conv.roles[0]: KeyError: 0
====================================================================================
same error too, thanks

**Comment by IApple233** [comment]
> /

I have encountered the same problem. Have you solved it?
